[versions]
netty = "4.2.16.Final"
log4j = "2.26.1"
slf4j = "2.0.18"
bouncycastle = "1.84"
annotations = "26.1.0"

[libraries]
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j2-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

bcprov-jdk18on = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
bcpkix-jdk18on = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncycastle" }

annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }

netty-handler = { module = "io.netty:netty-handler", version.ref = "netty" }

[bundles]
netty = ["netty-handler"]